version: '3.2'

networks:
  my-net:
    driver: bridge

services:
  crud-django:
    container_name: 'cotabest-django'
    image: cotabest-django
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always