# Generated by Django 4.1.3 on 2022-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimun', models.PositiveIntegerField(default=0)),
                ('amount_per_package', models.PositiveIntegerField(default=0)),
                ('max_availability', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name', 'price', 'id'),
            },
        ),
    ]
