# Generated by Django 4.1.3 on 2022-11-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuchaseItem',
            new_name='PurchaseItem',
        ),
    ]
